Dialectico.MVC/Controllers/MeaningController.cs
using Dialectico.Models;
using Dialectico.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dialectico.MVC.Controllers
{
    public class MeaningController : Controller
    {
        // GET: Meaning
        public ActionResult Index()
        {
            var service = new MeaningService();
            var model = service.GetAllMeanings();
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MeaningCreate model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            var service = new MeaningService();
            //service.CreateMeaning(model);
            return RedirectToAction("index");
        }


        //Get Edit
        public ActionResult MeaningEdit(int id)
        {
            var service = new MeaningService();
            var detail = service.GetMeaningById(id);
            
            return View(detail);
        }
        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MeaningListItem model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.MeaningId != id)
            {
                ModelState.AddModelError("", "Word is null");
                return View(model);
            }

            var service = new MeaningService();

            

            if (service.UpdateMeaning(model))
            {
                TempData["SaveResult"] = "Your note was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your meaning could not be updated.");
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var service = new MeaningService();
            var model = service.GetMeaningById(id);
            return View(model);
        }
        //Post Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMeaning(int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var service = new MeaningService();

            service.DeleteMeaning(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }

    }
}

Dialectico.MVC/Controllers/RootController.cs
using Dialectico.Data;
using Dialectico.Models;
using Dialectico.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dialectico.MVC.Controllers
{
    public class RootController : Controller
    {
       
        // GET: Root
        public ActionResult Index()
        {
            
            var service = new RootService();
            var model = service.GetRoots();
            return View(model);
        }
        //Get create
        public ActionResult Create()
        {
            return View();
        }
        //Post create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RootCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var service = new RootService();

            service.CreateRoot(model);

            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            var service = new RootService();
            var model = service.GetRootById(id);
            return View(model);
        }
        //Get Delete
        public ActionResult Delete(int id)
        {
            var service = new RootService();
            var model = service.GetRootById(id);
            return View(model);
        }
        //Post Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var service = new RootService();

            service.DeleteRoot(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var service = new RootService();
            var detail = service.GetRootById(id);
            var model =
                new RootListItem
                {
                    Id = detail.Id,
                    RootName = detail.RootName,
                    NotesOnRoot = detail.NotesOnRoot
                };
            return View(model);
        }
        //Get Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RootListItem model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = new RootService();

            if (service.UpdateRoot(model))
            {
                TempData["SaveResult"] = "Your note was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your note could not be updated.");
            return View(model);
        }

        public ActionResult Measures(int id)
        {
            var service = new RootService();
            var model = service.GetRootById(id);
            IEnumerable<string> measures = service.GetMeasures(id);
            if(model.Measures == null)
            { model.Measures = measures; }

            return View(model);
        }
    }
   

}

Dialectico.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dialecto - for Arabic learners</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dialecto", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                   
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li> @Html.ActionLink("Roots", "Index", "Root")</li>
                    <li> @Html.ActionLink("Words", "Index", "Word")</li>
                    <li> @Html.ActionLink("Meanings", "Index", "Meaning")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dialecto
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>